name: Deploying the package to NPM

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: Depra-Inc/Workflows/.github/workflows/deploy-npm.yml@main
    secrets:
      node_auth_token: ${{secrets.NPM_AUTH_TOKEN}}
      discord_webhook: ${{secrets.DISCORD_WEBHOOK}}